# Generated by Django 5.2.4 on 2025-07-22 01:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RondaPoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Nome do Ponto')),
                ('location_description', models.TextField(verbose_name='Descrição da Localização')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ronda_points', to='company.company')),
            ],
        ),
        migrations.CreateModel(
            name='RondaLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Data e Hora')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ronda_logs', to=settings.AUTH_USER_MODEL)),
                ('ronda_point', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='logs', to='mod_ronda.rondapoint')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
